/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.BalanceControllers;
import modelo.BalanceDAO;
import modelo.Egresos;
import modelo.Ingresos;

/**
 *
 * @author gchoj
 */
public class Jbalance extends javax.swing.JInternalFrame {

    Ingresos in = new Ingresos();
    Egresos eg = new Egresos();
    BalanceDAO bda = new BalanceDAO();
    public Jbalance() {
        initComponents();
        BalanceControllers bc = new BalanceControllers(in, eg, this, bda);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbegreso = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lbingreso = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lbutilidad = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbrentabilidad = new javax.swing.JLabel();
        datefin = new com.toedter.calendar.JDateChooser();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtegreso = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtingreso = new javax.swing.JTable();
        dateinicio = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();
        btnver = new javax.swing.JButton();
        txtinversion = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setTitle("Balance");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/linea-vertical.png"))); // NOI18N
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 30, 60, 100));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setText("Utilidad total");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, -1, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel6.setText("Q.");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, 30, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel7.setText("Egresos totales");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 90, -1, -1));

        lbegreso.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lbegreso.setForeground(new java.awt.Color(255, 0, 0));
        lbegreso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbegreso.setText("--------");
        jPanel2.add(lbegreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 120, 100, -1));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel9.setText("Q.");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 120, 20, -1));

        lbingreso.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lbingreso.setForeground(new java.awt.Color(0, 255, 51));
        lbingreso.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbingreso.setText("--------");
        jPanel2.add(lbingreso, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, 100, -1));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel11.setText("Ingresos totales");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel12.setText("Q.");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 20, -1));

        lbutilidad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        lbutilidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbutilidad.setText("-------");
        lbutilidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbutilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 130, -1));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/linea-vertical.png"))); // NOI18N
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 60, 100));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel8.setText("Rentabilidad");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 30, -1, -1));

        lbrentabilidad.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        lbrentabilidad.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbrentabilidad.setText("-------");
        lbrentabilidad.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel2.add(lbrentabilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 80, 150, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 80, 890, 160));
        jPanel1.add(datefin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 160, -1));

        jtegreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Tipo", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtegreso);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 260, 610, 260));

        jtingreso.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Tipo", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtingreso);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 520, 260));
        jPanel1.add(dateinicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 40, 160, -1));

        jLabel1.setText("Fin");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 40, -1, 20));

        jLabel2.setText("Seleccione el rango de fecha");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 10, -1, -1));

        jLabel3.setText("Inversión");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, 20));

        btnexit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/cross.png"))); // NOI18N
        btnexit.setBorder(null);
        btnexit.setContentAreaFilled(false);
        btnexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 0, 50, 40));

        btnver.setText("Ver");
        jPanel1.add(btnver, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 40, -1, -1));
        jPanel1.add(txtinversion, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 120, -1));

        jLabel13.setText("Inicio");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 40, -1, 20));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1170, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        this.hide();
    }//GEN-LAST:event_btnexitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnexit;
    public javax.swing.JButton btnver;
    public com.toedter.calendar.JDateChooser datefin;
    public com.toedter.calendar.JDateChooser dateinicio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jtegreso;
    public javax.swing.JTable jtingreso;
    public javax.swing.JLabel lbegreso;
    public javax.swing.JLabel lbingreso;
    public javax.swing.JLabel lbrentabilidad;
    public javax.swing.JLabel lbutilidad;
    public javax.swing.JTextField txtinversion;
    // End of variables declaration//GEN-END:variables
}
