/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.ComprasControllers;
import modelo.Compras;
import modelo.ComprasDAO;
import modelo.Proveedores;

/**
 *
 * @author gchoj
 */
public class Jcompras extends javax.swing.JInternalFrame {

    Compras com = new Compras();
    ComprasDAO comdao = new ComprasDAO();
    Proveedores prov = new Proveedores();
    public Jcompras() {
        initComponents();
        ComprasControllers ccr = new ComprasControllers(com, comdao, this, prov);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtcompras = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        txtbusqueda = new javax.swing.JTextField();
        btnalta = new javax.swing.JButton();
        btnbaja = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtid = new javax.swing.JTextField();
        txtestado = new javax.swing.JTextField();
        btlimpiar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btnmodificar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        cbestado = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txttotal = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtdescripcion = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        txtidproveedor = new javax.swing.JTextField();
        txtnombres = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtrazon = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtfactura = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        btnexit = new javax.swing.JButton();
        btnseleccionar = new javax.swing.JButton();
        datecompra = new com.toedter.calendar.JDateChooser();
        jLabel13 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtproveedor = new javax.swing.JTable();
        btncancelar = new javax.swing.JButton();
        btnseleccionarv = new javax.swing.JButton();
        txtbusquedap = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setTitle("Compras");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtcompras.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "ID proveedor", "Nombres", "Apellidos", "Razón", "Fecha", "Factura", "Descripción", "Total", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtcompras);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 960, 330));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/searching-bar (3).png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 30, 30));
        jPanel1.add(txtbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 240, 160, 20));

        btnalta.setText("Ver compras de ALTA");
        jPanel1.add(btnalta, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 610, -1, -1));

        btnbaja.setText("Ver compras de BAJA");
        btnbaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbajaActionPerformed(evt);
            }
        });
        jPanel1.add(btnbaja, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 610, -1, -1));

        jLabel2.setText("Buscar por fecha");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, -1, -1));
        jPanel1.add(txtid, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 240, 30, -1));
        jPanel1.add(txtestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 240, 30, -1));

        btlimpiar.setText("Limpiar");
        jPanel1.add(btlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 607, 100, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnmodificar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/updating.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.setBorder(null);
        btnmodificar.setContentAreaFilled(false);
        btnmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnmodificar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jPanel3.add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 60, 60));

        btnguardar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/diskette.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setBorder(null);
        btnguardar.setContentAreaFilled(false);
        btnguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnguardar.setVerifyInputWhenFocusTarget(false);
        btnguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnguardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnguardarMouseExited(evt);
            }
        });
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });
        jPanel3.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 130, 60, 60));

        cbestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALTA", "BAJA" }));
        jPanel3.add(cbestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 90, 80, 20));

        jLabel6.setText("Estado *");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 70, -1, 10));
        jPanel3.add(txttotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 90, -1));

        jLabel10.setText("Fecha *");
        jPanel3.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 70, -1, -1));

        txtdescripcion.setColumns(20);
        txtdescripcion.setLineWrap(true);
        txtdescripcion.setRows(5);
        txtdescripcion.setWrapStyleWord(true);
        jScrollPane1.setViewportView(txtdescripcion);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 300, 110));

        jLabel5.setText("Descripción");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 90, -1));
        jPanel3.add(txtidproveedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 60, 30, -1));
        jPanel3.add(txtnombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 30, 220, -1));

        jLabel1.setText("Nombres");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 10, -1, -1));

        txtrazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtrazonActionPerformed(evt);
            }
        });
        jPanel3.add(txtrazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 30, 220, -1));

        jLabel3.setText("Razon");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 10, -1, -1));
        jPanel3.add(txtfactura, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 30, 170, -1));

        jLabel9.setText("No. Factura *");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 10, -1, -1));

        btnexit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/cross.png"))); // NOI18N
        btnexit.setBorder(null);
        btnexit.setContentAreaFilled(false);
        btnexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel3.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 10, 50, 40));

        btnseleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/selecciones-de-personal.png"))); // NOI18N
        jPanel3.add(btnseleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));
        jPanel3.add(datecompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 150, -1));

        jLabel13.setText("Total *");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 70, -1, -1));

        jTabbedPane1.addTab("Registro de Compra", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtproveedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombres", "Apellidos", "Razón", "Descripción"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jtproveedor);

        jPanel4.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, 620, 150));

        btncancelar.setText("Cancelar");
        jPanel4.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 10, 100, -1));

        btnseleccionarv.setText("Seleccionar");
        jPanel4.add(btnseleccionarv, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 10, -1, -1));
        jPanel4.add(txtbusquedap, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 160, 20));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/searching-bar (3).png"))); // NOI18N
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 20, 30, 30));

        jLabel12.setText("Buscar por nombre");
        jPanel4.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, -1, -1));

        jTabbedPane1.addTab("Selección de Proveedor", jPanel4);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 810, 230));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnguardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseEntered
        //    btnguardar.setContentAreaFilled(true);
    }//GEN-LAST:event_btnguardarMouseEntered

    private void btnguardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseExited
        //    btnguardar.setContentAreaFilled(false);
    }//GEN-LAST:event_btnguardarMouseExited

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        this.hide();
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnbajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnbajaActionPerformed

    private void txtrazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtrazonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtrazonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btlimpiar;
    public javax.swing.JButton btnalta;
    public javax.swing.JButton btnbaja;
    public javax.swing.JButton btncancelar;
    private javax.swing.JButton btnexit;
    public javax.swing.JButton btnguardar;
    public javax.swing.JButton btnmodificar;
    public javax.swing.JButton btnseleccionar;
    public javax.swing.JButton btnseleccionarv;
    public javax.swing.JComboBox<String> cbestado;
    public com.toedter.calendar.JDateChooser datecompra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jtcompras;
    public javax.swing.JTable jtproveedor;
    public javax.swing.JTextField txtbusqueda;
    public javax.swing.JTextField txtbusquedap;
    public javax.swing.JTextArea txtdescripcion;
    public javax.swing.JTextField txtestado;
    public javax.swing.JTextField txtfactura;
    public javax.swing.JTextField txtid;
    public javax.swing.JTextField txtidproveedor;
    public javax.swing.JTextField txtnombres;
    public javax.swing.JTextField txtrazon;
    public javax.swing.JTextField txttotal;
    // End of variables declaration//GEN-END:variables
}
