/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;


import controlador.CreditosgeneralControllers;
import modelo.CreditoreporteDAO;
import modelo.Creditos;

/**
 *
 * @author gchoj
 */
public class Jcontrolcredito extends javax.swing.JInternalFrame {

    /**
     * Creates new form JControlcredito
     */
    
    Creditos cred = new Creditos();
    CreditoreporteDAO credao = new CreditoreporteDAO();
    
    public Jcontrolcredito() {
        initComponents();
        CreditosgeneralControllers cr = new CreditosgeneralControllers(this, credao, cred);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnreporte = new javax.swing.JButton();
        btnexit = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtcredito = new javax.swing.JTable();
        cbclientes = new javax.swing.JComboBox<>();
        btnlistar = new javax.swing.JButton();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnreporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/pdf.png"))); // NOI18N
        btnreporte.setBorder(null);
        btnreporte.setContentAreaFilled(false);
        jPanel1.add(btnreporte, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 0, 50, 50));

        btnexit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/cross.png"))); // NOI18N
        btnexit.setBorder(null);
        btnexit.setContentAreaFilled(false);
        btnexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 40, 50));

        jtcredito.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Vendedor", "Dirección", "Teléfono", "Fecha crédito", "Total", "Pendiente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jtcredito);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 50, 1010, 520));

        cbclientes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una opción", "Clientes No Morosos", "Clientes Morosos" }));
        jPanel1.add(cbclientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btnlistar.setText("Listar");
        jPanel1.add(btnlistar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 20, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1030, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        this.hide();
    }//GEN-LAST:event_btnexitActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnexit;
    public javax.swing.JButton btnlistar;
    public javax.swing.JButton btnreporte;
    public javax.swing.JComboBox<String> cbclientes;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jtcredito;
    // End of variables declaration//GEN-END:variables
}
