/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.CreditosControllers;
import modelo.Creditodetalle;
import modelo.Creditos;
import modelo.CreditosDAO;
import modelo.Productos;

/**
 *
 * @author gchoj
 */
public class Jcreditosdetalle extends javax.swing.JInternalFrame {

    Creditos cred = new Creditos();
    CreditosDAO credao = new CreditosDAO();
    Creditodetalle credat = new Creditodetalle();
    Productos prod = new Productos();

    public Jcreditosdetalle() {
        initComponents();
        CreditosControllers ccr = new CreditosControllers(cred, credao, credat, this, prod);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtcreditodetalle = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        lbtotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtcreditos = new javax.swing.JTable();
        btnmodificar = new javax.swing.JButton();
        cbestado = new javax.swing.JComboBox<>();
        btnexit = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        btneliminar = new javax.swing.JButton();
        btnguardar = new javax.swing.JButton();
        txtprecio = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtcantidad = new javax.swing.JTextField();
        txtdireccion = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtnombrecliente = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtproducto = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtidproducto = new javax.swing.JTextField();
        txtidcliente = new javax.swing.JTextField();
        btnseleccionarprod = new javax.swing.JButton();
        btnseleccionarcliente = new javax.swing.JButton();
        datecredito = new com.toedter.calendar.JDateChooser();
        jLabel7 = new javax.swing.JLabel();
        btnseleccionarvendedor = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtnombrevendedor = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        txtapellidovendedor = new javax.swing.JTextField();
        txtidvendedor = new javax.swing.JTextField();
        txtidcredito = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtclientes = new javax.swing.JTable();
        btncancelar = new javax.swing.JButton();
        btnseleccionarv = new javax.swing.JButton();
        txtbusqueda = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jtproducto = new javax.swing.JTable();
        btnseleccionarp = new javax.swing.JButton();
        btncancelarp = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jtvendedor = new javax.swing.JTable();
        btnseleccionarven = new javax.swing.JButton();
        btncancelarven = new javax.swing.JButton();
        txtbusquedavendedor = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtabono = new javax.swing.JTable();

        setTitle("Créditos");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtcreditodetalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Cantidad", "Precio", "Total"
            }
        ));
        jScrollPane1.setViewportView(jtcreditodetalle);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 10, 530, 250));

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        jLabel5.setText("Total Crédito");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 270, -1, -1));

        lbtotal.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 14)); // NOI18N
        lbtotal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbtotal.setText("----");
        jPanel1.add(lbtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 270, 90, -1));

        jtcreditos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre vendedor", "Apellido vendedor", "Nombre cliente", "Apellido cliente", "Fecha", "Total", "Pendiente", "Estado"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jtcreditos);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 980, 270));

        btnmodificar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        btnmodificar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/updating.png"))); // NOI18N
        btnmodificar.setText("Modificar");
        btnmodificar.setBorder(null);
        btnmodificar.setContentAreaFilled(false);
        btnmodificar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnmodificar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(btnmodificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 300, 100, 40));

        cbestado.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione", "BAJA" }));
        jPanel1.add(cbestado, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 340, 110, -1));

        btnexit.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        btnexit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/cross.png"))); // NOI18N
        btnexit.setBorder(null);
        btnexit.setContentAreaFilled(false);
        btnexit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnexit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnexitActionPerformed(evt);
            }
        });
        jPanel1.add(btnexit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 0, 40, 40));

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btneliminar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        btneliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/bin.png"))); // NOI18N
        btneliminar.setText("Eliminar");
        btneliminar.setBorder(null);
        btneliminar.setContentAreaFilled(false);
        btneliminar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btneliminar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btneliminar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btneliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btneliminarActionPerformed(evt);
            }
        });
        jPanel3.add(btneliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 210, 50, 50));

        btnguardar.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/diskette.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setBorder(null);
        btnguardar.setContentAreaFilled(false);
        btnguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnguardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnguardar.setVerifyInputWhenFocusTarget(false);
        btnguardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnguardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnguardarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnguardarMouseExited(evt);
            }
        });
        jPanel3.add(btnguardar, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 210, 60, 50));
        jPanel3.add(txtprecio, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 60, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel4.setText("Precio");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel3.setText("Cantidad");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 10, -1, -1));
        jPanel3.add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 70, -1));
        jPanel3.add(txtdireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 220, -1));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel8.setText("Dirección del cliente");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 60, -1, -1));
        jPanel3.add(txtnombrecliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, 210, -1));

        jLabel6.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel6.setText("Fecha del crédito");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, -1, -1));
        jPanel3.add(txtproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 210, -1));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel2.setText("Producto");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
        jPanel3.add(txtidproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 30, -1));
        jPanel3.add(txtidcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 60, 20, -1));

        btnseleccionarprod.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/agregar-producto.png"))); // NOI18N
        btnseleccionarprod.setContentAreaFilled(false);
        jPanel3.add(btnseleccionarprod, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        btnseleccionarcliente.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/delegar.png"))); // NOI18N
        btnseleccionarcliente.setContentAreaFilled(false);
        jPanel3.add(btnseleccionarcliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel3.add(datecredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 130, 170, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel7.setText("Nombres del cliente");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, -1, -1));

        btnseleccionarvendedor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/selecciones-de-personal.png"))); // NOI18N
        btnseleccionarvendedor.setContentAreaFilled(false);
        jPanel3.add(btnseleccionarvendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel11.setText("Nombres del vendedor");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, -1, 20));
        jPanel3.add(txtnombrevendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, 180, 20));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 11)); // NOI18N
        jLabel12.setText("Apellidos del vendedor");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, -1));
        jPanel3.add(txtapellidovendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 180, -1));

        txtidvendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtidvendedorActionPerformed(evt);
            }
        });
        jPanel3.add(txtidvendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 180, 30, -1));
        jPanel3.add(txtidcredito, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 60, -1));

        jTabbedPane1.addTab("Agregar Crédito", jPanel3);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtclientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombres", "Apellidos", "Dirección", "Teléfono"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jtclientes);

        jPanel4.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 510, 170));

        btncancelar.setText("Cancelar");
        jPanel4.add(btncancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 10, 100, -1));

        btnseleccionarv.setText("Seleccionar");
        jPanel4.add(btnseleccionarv, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));
        jPanel4.add(txtbusqueda, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 160, 20));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/searching-bar (3).png"))); // NOI18N
        jPanel4.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        jLabel10.setText("Buscar por nombre");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        jTabbedPane1.addTab("Selección Cliente", jPanel4);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtproducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Producto", "Descripcion", "Precio venta"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jtproducto);

        jPanel2.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 500, 180));

        btnseleccionarp.setText("Seleccionar");
        jPanel2.add(btnseleccionarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        btncancelarp.setText("Cancelar");
        jPanel2.add(btncancelarp, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 100, -1));

        jTabbedPane1.addTab("Selección Producto", jPanel2);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jtvendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "Apellido", "Tipo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(jtvendedor);

        jPanel5.add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 500, 180));

        btnseleccionarven.setText("Seleccionar");
        jPanel5.add(btnseleccionarven, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 10, -1, -1));

        btncancelarven.setText("Cancelar");
        jPanel5.add(btncancelarven, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, 100, -1));
        jPanel5.add(txtbusquedavendedor, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 160, 20));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icono/searching-bar (3).png"))); // NOI18N
        jPanel5.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 30, 30));

        jLabel14.setText("Buscar por nombre");
        jPanel5.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, -1));

        jTabbedPane1.addTab("Selección vendedor", jPanel5);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 530, 330));

        jtabono.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jtabono);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 470, 70, 90));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1130, 570));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnexitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnexitActionPerformed
        this.hide();
    }//GEN-LAST:event_btnexitActionPerformed

    private void btnguardarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseEntered
        //    btnguardar.setContentAreaFilled(true);
    }//GEN-LAST:event_btnguardarMouseEntered

    private void btnguardarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnguardarMouseExited
        //    btnguardar.setContentAreaFilled(false);
    }//GEN-LAST:event_btnguardarMouseExited

    private void btneliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btneliminarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btneliminarActionPerformed

    private void txtidvendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtidvendedorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtidvendedorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btncancelar;
    public javax.swing.JButton btncancelarp;
    public javax.swing.JButton btncancelarven;
    public javax.swing.JButton btneliminar;
    private javax.swing.JButton btnexit;
    public javax.swing.JButton btnguardar;
    public javax.swing.JButton btnmodificar;
    public javax.swing.JButton btnseleccionarcliente;
    public javax.swing.JButton btnseleccionarp;
    public javax.swing.JButton btnseleccionarprod;
    public javax.swing.JButton btnseleccionarv;
    public javax.swing.JButton btnseleccionarven;
    public javax.swing.JButton btnseleccionarvendedor;
    public javax.swing.JComboBox<String> cbestado;
    public com.toedter.calendar.JDateChooser datecredito;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    public javax.swing.JTabbedPane jTabbedPane1;
    public javax.swing.JTable jtabono;
    public javax.swing.JTable jtclientes;
    public javax.swing.JTable jtcreditodetalle;
    public javax.swing.JTable jtcreditos;
    public javax.swing.JTable jtproducto;
    public javax.swing.JTable jtvendedor;
    public javax.swing.JLabel lbtotal;
    public javax.swing.JTextField txtapellidovendedor;
    public javax.swing.JTextField txtbusqueda;
    public javax.swing.JTextField txtbusquedavendedor;
    public javax.swing.JTextField txtcantidad;
    public javax.swing.JTextField txtdireccion;
    public javax.swing.JTextField txtidcliente;
    public javax.swing.JTextField txtidcredito;
    public javax.swing.JTextField txtidproducto;
    public javax.swing.JTextField txtidvendedor;
    public javax.swing.JTextField txtnombrecliente;
    public javax.swing.JTextField txtnombrevendedor;
    public javax.swing.JTextField txtprecio;
    public javax.swing.JTextField txtproducto;
    // End of variables declaration//GEN-END:variables
}
